### ISSUE TITLE
local games and data

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#1]
This issue covers general features needed to get local games added to the client.

- [x] Empty Game/UID with TItle, creator and version as requirements.
- [x] Decription Metadata
- [x] Tags
- [x] exe/game path to launch (should support a steam launch command with a steam id in the future)
- [x] Additional parameters for executable launch (Something like steam's parameter feature. See [Runtime Config Options](https://github.com/ValveSoftware/Proton#runtime-config-options)  )
- [x] Main Thumbnails
- [x] Gallery/Preview thumbnails/gallery

**Comment by KJNeko** [comment]
Completed. Awaiting merge with editor-dev
