### ISSUE TITLE
Add version does not add the version to the lists.

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#12]
Add version does not add the version to the lists.

Trying to add a new version to an already existing game does not add it to the version lists.

This is with [v0.2.2-alpha-7](https://github.com/KJNeko/Hydrus95/releases/tag/v0.2.2-alpha-7)

![image](https://user-images.githubusercontent.com/8496821/222222605-3a55c3e3-6cc4-4424-a816-5326b6cba75b.png)
![image](https://user-images.githubusercontent.com/8496821/222222651-fe4d8cee-ed74-483e-b7dc-66da1e375062.png)
![image](https://user-images.githubusercontent.com/8496821/222222693-b1b9a539-2e71-4114-a8cd-5f61df21b580.png)

Files where copied correctly still though! 
![image](https://user-images.githubusercontent.com/8496821/222222767-572d8ff8-6c37-42f6-b823-abb16701a18d.png)

**Comment by KJNeko** [comment]
Fixed as it is now quite literally impossible for this to occur anymore except in situations where it's a visual bug. GUI should now properly update when importing so this also should just not happen anymore.
