### ISSUE TITLE
entries in the scanner list cant be selected and deleted

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#131]
Entries in the scanner for the bulk install window does not select the line/item itself so it can't be deleted.
Clicking the number on the left which has no field should select the entire line so you can remove bad actors, 
this selects the title text instead. 

Tried to do a refresh scan and wanted to remove all the duplicate versions in the version column that got warnings to "resume" my import.
![image](https://github.com/KJNeko/Atlas/assets/8496821/5ac8a426-e8d4-4a94-8cc7-862b742591d5)

**Comment by KJNeko** [comment]
Needs testing.

**Comment by CuddleBear92** [comment]
this seems to have been fixed! you can select the row as a whole now and delete them as described in the issue!
found an UI issue to the selection, making a new issue about it!
