### ISSUE TITLE
thumbnails is stair stepping and is generally low quality/blocking

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#134]
thumbnails is stair stepping and is generally low quality/blocking
some examples:
![image](https://github.com/KJNeko/Atlas/assets/8496821/8f5a816e-d15b-4da8-83ae-58d5c24f0de8)
![image](https://github.com/KJNeko/Atlas/assets/8496821/fbcc99f3-b3f2-41bb-9ac1-d7c501c12696)
![image](https://github.com/KJNeko/Atlas/assets/8496821/515784a4-414a-4115-b60a-87053faf1bc4)
![image](https://github.com/KJNeko/Atlas/assets/8496821/2f37e60b-77e3-496c-bbac-44bde15f89d0)
![image](https://github.com/KJNeko/Atlas/assets/8496821/cb79a49b-ccdc-441f-b6cf-597cf64bb967)
![image](https://github.com/KJNeko/Atlas/assets/8496821/ff4d5ce0-7c54-41d7-86b7-00caf28aa2e1)

**Comment by KJNeko** [comment]
Fix done in staging.
