### ISSUE TITLE
add an edit button on details page

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#14]
The details page should have an edit button for an alternative way to enter the editing mode instead of just having it on the context menu of the gallery.

Unsure where to place this button. maybe next to the exit button? or opposite side? 
![image](https://user-images.githubusercontent.com/8496821/222224222-3ea2bf71-cd61-4e28-a4fd-ff22859194ab.png)

**Comment by KJNeko** [comment]
Closed since we've had this for a bit now.
