### ISSUE TITLE
Dark Mode/QSS Support!

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#17]
add a Dark Mode or QSS support so we are not blinded by the default white theme.

**Comment by KJNeko** [comment]
Did some light looking to this. 

The most basic way to do this would be to simply call. 
[QApplication::setStyleSheet()](https://doc.qt.io/qt-6/qapplication.html#styleSheet-prop)

Loading the system theme would however be the preferred option

The [QStyleFactory](https://doc.qt.io/qt-6/qstylefactory.html) seems to be the best way to me to integrate directly with the system theme for both windows and linux. Will have to check what styles windows offers. Hopefully one is a dark theme.

**Comment by towerwatchman** [comment]
V1 Complete. Will make changes as we go
