### ISSUE TITLE
F95zone scraping

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#2]
This issue covers general feature requirements for F95 scraping.

- [x] save thread id as a thread id value (urls are generated from these)
- [x] Grab the Title
- [x] Grab the Creator
- [x] Grab the Tags
- [x] Grab the Version Value
- [x] Grab the release date
- [x] Grab the community rating
- [x] Grab the number of views
- [x] Grab the number of likes
- [x] Grab the Supported Languages
- [x] Grab the Supported OS for the game
- [x] Grab the last OP Edit date from post metadata (not from thread updated value, would think that could be wrong)
- [x] Grab the main banner/thumbnail and/or url
- [x] Grab urls of preview images/gallery
- [x] Grab Description/Overview from the OP
- [ ] Grab the Changelog
- [ ] Grab Download URL's
- [ ] Pull the RSS feeds to keep client updated
- [ ] Grabbing External URL's Like Steam or DLSite for games or Daz3D, Renderosity or Renderotica for assets and maybe others.

Links to Scrape: https://f95zone.to/sam/latest_alpha/latest_data.php?cmd=list&cat=games&page=1&sort=date&rows=90

**Comment by towerwatchman** [comment]
I'm working on this now.  As this progresses ill put updates here. Right now I am scraping the following

- f95_id <- thread id
- other 
- engine
- banner_url
- title
- status
- version
- developer <- creator
- site_url
- thread_update
- release_date
- censored     
- language
- translations
- length
- voice
- os

**Comment by CuddleBear92** [comment]
this might be useful? 
https://github.com/MillenniumEarl/F95API
https://f95zone.to/threads/f95-api.66994/
