### ISSUE TITLE
Auto determine engine type

### ISSUE THREAD

**Issue by KJNeko** [KJNeko/Atlas#21]
- [x] #22
- [x] #23
- [x] #24
- [x] Wolf RPG
    I have no clue. `wolf` seems to be a valid string but I need to test more if it's in all of the executables.
- [x] Unreal Engine 4 and 5
   - [x] Check for manifest text file next to exe
- [x] HTML Games (launching with an html file?)
- [x] Visual Novel Maker
- [x] #27 
- [x] Java (launching with .jar?)
- [x] Flash (launching with a SWF file?)
- [x] RAGS
- [x] QSP
- [x] KiriKiri
- [x] NScripter
- [x] NVList
- [x] Suika2

**Comment by towerwatchman** [comment]
We can use the types for the repo below. It will make this entire process so much easier.
https://steamdb.info/tech/
https://github.com/SteamDatabase/FileDetectionRuleSets

**Comment by towerwatchman** [comment]
Will need to add a new feature to download swf/flv player. ruffle is probably the best.
