### ISSUE TITLE
Game-List transfer utility

### ISSUE THREAD

**Issue by KJNeko** [KJNeko/Atlas#29]
Not sure how we missed making this an issue however we should probably make something to easily transfer from GL to Atlas

**Comment by CuddleBear92** [comment]
All GL installs got an `GL_Infos.ini` file that contains the normalized thread url, version value and title which you can use for scanning without needing to access the GL DB.
This file is placed next to the exe no matter the folder scheme.


Attaching an example file (had to zip it up as it was not supported as is)
[GL_Infos.zip](https://github.com/KJNeko/Atlas/files/11222528/GL_Infos.zip)
![image](https://user-images.githubusercontent.com/8496821/231769916-7303d424-9ef9-4332-8e26-bdcf2c8034a0.png)

**Comment by CuddleBear92** [comment]
ini importing is in the install process now
