### ISSUE TITLE
being able to kill open games within Atlas

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#55]
I think we should be able to kill or close open titles from within Atlas. 

Like how Steam does it: 
![image](https://github.com/KJNeko/Atlas/assets/8496821/7cb87232-18cf-44ef-b7b9-2a2f04347782)

This could replace the play button in the detailed page. but this could also be listed in another location where it lists all the open titles.
Having an option to close the open games when you manually close Atlas would also make sense here!

Guess it would look at the open tasks based on the exe filename. maybe ping the open processes once a sec or once every 5 sec?

**Comment by towerwatchman** [comment]
Added ability to close games from game details screen
