### ISSUE TITLE
remove the size column from the bulk import window

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#58]
Since filesizes is calculated in a background maintenance task as files are getting moved around on the final step.
Having them be scanned at this step does not make sense and have been currently turned off for speedier imports.
Leftover UI is still there in the form of the size column which should be removed.

![image](https://github.com/KJNeko/Atlas/assets/8496821/b477217d-82be-461f-92a5-f46a17dff82e)

**Comment by KJNeko** [comment]
Size column now hides itself if the user chooses to not process the sizes yet.
