### ISSUE TITLE
Bulk Installing

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#6]
This issue covers features for bulk installing.

- [x] Ability to Scan director and dive down.
- [x] Have the install directory scheme be used as a scanning blueprint (using say D:gamefolder/TITLE/CREATOR/VERSION/game.exe
- [x] Lay out all paths in a list for confirmation (this will have the ability to change the fields per row like titles, creator and versions, should also have an remove or skip option if the user have to wait with the specific row)
- [ ] Bulk extraction? (could maybe enforce a required naming scheme of the archive (like matching the thread name with creator and version value for easier matching))

**Comment by KJNeko** [comment]
Move bulk extraction to a new issue. It's a less-needed feature and more of a 'nice to have'
