### ISSUE TITLE
detailed page preview gallery rendering issues

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#60]
There is some rendering issues with the detailed page gallery. 
It seems to be using the WIDEST image as the basis of all the images.
So no matter the width of the other images they will be next to each other even if there is space for it.
Bellow in the images, the previews should be next to each other. But since the banner is wide, it thinks all of them are just as wide?
Also why do we even have the banner there when its rendered at the top anyway? 🤔 

![image](https://github.com/KJNeko/Atlas/assets/8496821/abc8c8bc-82c1-4e77-99cc-5cf93654137c)
![image](https://github.com/KJNeko/Atlas/assets/8496821/1d3873c1-8fa2-4672-9cd8-4ce2712122c3)
![image](https://github.com/KJNeko/Atlas/assets/8496821/dbc86f7d-ff26-4696-9638-7bbcd27358ae)

**Comment by towerwatchman** [comment]
Im moving this to 1.0. This is going to required additional work in order for it to work properly

**Comment by towerwatchman** [comment]
This is tied to #127 but needs to have the hover effect removed. @KJNeko are we planning to open the image if it is clicked on?
