### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by KJNeko** [KJNeko/Atlas#66]
We are having quite a lot of regression issues. To prevent this we should strictly unit test and eventually integrate it into PR checks.

- [ ] Core tests
- [ ] Network tests (Might also test the remote itself daily)
- [ ] GUI tests

**Comment by CartographicCorsair** [comment]
Working on breaking up the **CMakeLists.txt** file to make this process cleaner.

**Comment by KJNeko** [comment]
Qt makes this a living he'll. So no.
