### ISSUE TITLE
QWebpHandler::write() source image too large for WebP:  QSize(3654, 27679)

### ISSUE THREAD

**Issue by CartographicCorsair** [KJNeko/Atlas#67]
Issue found by @KJNeko . More information needed.

**Comment by KJNeko** [comment]
Probably need to check for the max size that WebP can handle. Apparently it's not too large 
![image](https://github.com/KJNeko/Atlas/assets/36950324/4820f669-2114-4380-9243-f70012b64044)
Might need to write some bypass for when the image is too large for webp

**Comment by KJNeko** [comment]
Issue occurs here. In the case that this happens (Check manually for size above ~16k) we should just use whatever the original image was provided.
https://github.com/KJNeko/Atlas/blob/4f77504929a6dff0adbf3a40e620a056c9a5dc35/atlas/core/imageManager.cpp#L100-L104

**Comment by KJNeko** [comment]
Found the source of the issue with my testing data specifically. Apparently I have a PDF in my preview images. We might want to add that as just another bypass like we did with gifs.
