### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by KJNeko** [KJNeko/Atlas#74]
The right click menu needs to be refactored and setup to work properly. Adding a version should open a version of the SingleImporter that has some of the fields locked and auto populated with the information from the record itself.

CuddleBear EDIT:
The Right click menu should contain a handful of buttons and options.

- [x] A play button that shows all versions. user can select version to play
- [x ] A button to open urls with a similar expansion menu (maybe?) if there is more than one url (setting to have a whitelist or blacklist of shown urls?)
- [x] A button to open the directory of the installed game.

**Comment by towerwatchman** [comment]
more settings moved to 1.0
