### ISSUE TITLE
storage stats/graph

### ISSUE THREAD

**Issue by CuddleBear92** [KJNeko/Atlas#8]
A page for storage stats and a graph would be nice.
Total amount of storage used by all your installed games, monthly and session based counter that lowers when you delete a version and increase when you install a version. 
This way you can easily see how much you are doing each time you process your backlog.

This should pretty much just count the size of what you are uninstalling and installing and logging these size values.

**Comment by KJNeko** [comment]
Implemented a bit ago. Forgot to close. Very basic for now. More features can come later. Create new issues for additional features to this.
