### ISSUE TITLE
0.5 beta Rolling Issues List

### ISSUE THREAD

**Issue by towerwatchman** [KJNeko/Atlas#85]
- [x] Fix game size not being populated in the database
- [x] Update options for threading menu in settings dialog or disable
- [x] Fix message handler in windows. It will not close, buttons don't work and it is not anchored
- [x] Fix Staging GH Action to build once pushed. Should start at 0.5
- [x] GH readme needs to be modified to reflect changes to project
- [x] Status Icons on GH need to be fixed. Not sure they are working
- [x] Right Clicking the main view with no items loaded will cause the program to crash
- [x] The themes folder is not set in the correct location. should be ./data/themes -> add check for ./themes
- [x] webp conversion is not working. It reads webp without any issues.

**Comment by Revan67** [comment]
.rag .jar .qsp .bat  still not being seen as a valid executable.

Atlas still not seeing .EXE

![image](https://github.com/KJNeko/Atlas/assets/8174203/f109d206-c457-421f-b347-a180ec55b700)
